name: push

on: pull_request

jobs:
    first_job:
        runs-on: macos-latest
        steps:
            - name: first_step
              run: pwd

            - name: second_step
              run: ls
    
    second_job:
        runs-on: macos-latest
        steps:
            - name: first_step2
              run: echo '${{ toJson(github) }}'