name: "push"

on: push

jobs:
    first_job:
        runs-on: macos-latest
        steps:
            - name: first_step
              run: echo "Hello, Wolrd!"

            - name: second_step
              run: echo '${{ toJson(github) }}'
    
    second_job:
        runs-on: macos-latest
        steps:
            - name: first_step2
              run: echo "running first_step2"